version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    entrypoint: ["/bin/sh", "/wait-for-edges.sh", "--", "cdn_client"]
    container_name: CLIENT
    command:
      - "--server-addr=:9090" # server address for prometheus
      # - "--origin-addr=origin:8080" # server address for origin
      - "--origin-addrs=frontend1:80,frontend2:80" # server address for varnish
      - "--wiki-file=/data/wiki_test.csv"
      - "--log-level=debug"
      - "--cpus=1"
    ports:
      - "9090:9090"
    volumes:
      - ./cmd/client/wiki_test.csv:/data/wiki_test.csv
      - ./internal/client/wait-for-edges.sh:/wait-for-edges.sh
      - ./logs:/var/log
    depends_on:
      - origin
      - frontend1
      - frontend2
      - edge-backend
    networks:
      - mynetwork

  origin:
    build:
      context: .
      dockerfile: cmd/origin/Dockerfile
    entrypoint: ["cdn_origin"]
    container_name: ORIGIN
    command:
      - "--server-port=8080"
      - "--log-level=debug"
      - "--cpus=1"
    volumes:
      - ./logs:/var/log
    networks:
      - mynetwork
  
  frontend1:
    image: varnish:latest
    container_name: L1_1
    volumes:
      - ./scene/cache-node/frontend/toATS.vcl:/etc/varnish/toATS.vcl
      - varnish_storage1:/var/lib/varnish:rw
      - ./logs:/var/log/varnish
    command: >
      -f /etc/varnish/toATS.vcl -s file,/var/lib/varnish/varnish_storage1.bin,10m
    ports:
      - "10080:80"
    depends_on:
      - origin
    networks:
      - mynetwork

  # frontend1_log:
  #   image: varnish:latest
  #   container_name: L1_1_LOG
  #   depends_on:
  #     - frontend1
  #   volumes:
  #     - ./logs:/var/log/varnish
  #   command: varnishlog
  #   networks:
  #     - mynetwork
  
  frontend2:
    image: varnish:latest
    container_name: L1_2
    volumes:
      - ./scene/cache-node/frontend/toATS.vcl:/etc/varnish/toATS.vcl
      - varnish_storage2:/var/lib/varnish:rw
    command: >
      -f /etc/varnish/toATS.vcl -s file,/var/lib/varnish/varnish_storage2.bin,10m
    ports:
      - "10081:80"
    depends_on:
      - origin
    networks:
      - mynetwork
  
  edge-backend:
    build:
      context: .
      dockerfile: scene/trafficserver/Dockerfile
    container_name: L2_1
    volumes:
      - ./scene/cache-node/backend/records.config:/etc/trafficserver/records.config
      - ./scene/cache-node/backend/remap.config:/etc/trafficserver/remap.config
      - ./scene/cache-node/backend/storage.config:/etc/trafficserver/storage.config
      - ./scene/cache-node/backend/plugin.config:/etc/trafficserver/plugin.config
      - ./scene/cache-node/backend/magnition_header.lua:/etc/trafficserver/magnition_header.lua
      - ./logs:/var/log/trafficserver
    ports:
      - "20080:8080"
    depends_on:
      - origin
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    container_name: STATS
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - mynetwork

volumes:
  varnish_storage1:
  varnish_storage2:


networks:
  mynetwork:
    driver: bridge
